#!/bin/bash
#
# mk2f - sshfs-utils
#
# Copyright (c) 2021, Francis Turner
# All rights reserved.
#
# create the sshfs mountpoint /mnt/ssh/PARM1 accessed as PARM2 and store
# the config in ~/.config/sshfs/PARM1.
# Once created it is then mounted by executing 2f
#
# If no parameter give help
#
if [ ${#*} -ne 2 ]
then
	echo "Usage: $0 mountpoint 'user@host:/path'"
	exit 1
fi
if [ -d /mnt/ssh/$1 ]
then
	echo "Mpuntpoint $1 already exists"
	exit 1
fi
if [ -f ~/.config/sshfs/$1 ]
then
	echo "Mountpoint $1 not found but has ssh map info"
	exit 1
fi

echo "Creating mountpoint (/mnt/ssh/)$1 mapping to $2"
mkdir "/mnt/ssh/$1"
echo $2 > ~/.config/sshfs/$1
echo "testing..."
2f $1
