#!/bin/bash
#
# mk2f - sshfs-utils
#
# Copyright (c) 2021, Francis Turner
# All rights reserved.
#
# create the sshfs mountpoint /mnt/ssh/PARM1 accessed as PARM2 and store
# the config in ~/.config/sshfs/PARM1.
# Once created it is then mounted by executing 2f
#
# If no parameter give help
#

if [ ${#*} -lt 2 ]
then
	echo "Usage: $0 mountpoint 'user@host:/path'"
	exit 1
fi
if [ -d /mnt/ssh/$1 ]
then
	echo "Mountpoint $1 already exists"
	exit 1
fi
if [ -f ~/.config/sshfs/$1 ]
then
	echo "Mountpoint $1 not found but has ssh map info"
	exit 1
fi

if [[ $2 =~ \@([0-9]+(\.[0-9]+)?): ]]
then
	HOSTIP=${BASH_REMATCH[1]}
	#echo $HOSTIP
	if [[ $HOSTIP == *"."* ]]
	then
		FH=`hostname -I | sed 's/\([1-9][0-9.]*\.\)[1-9][0-9.]*\..*/\1'$HOSTIP'/'`
	else
		FH=`hostname -I | sed 's/\([1-9][0-9.]*\.\).*/\1'$HOSTIP'/'`
	fi
	MP=`echo $2|sed 's/'$HOSTIP'/'$FH'/'`
	#echo "mounting $MP"
else
	MP=${@:2}
fi
echo "Check connecticity by ssh and ls of $MP ? (y/N)"
read  ANSWER
if [ "$ANSWER" != "${ANSWER#[Yy]}" ] ;then
	echo $MP | sed 's/^\([^:]*\):/ssh \1 ls /' | sh
	read -p "Did that work? (y/N)" ANSWER
	if [ "$ANSWER" == "${ANSWER#[Yy]}" ] ;then
		echo "Quitting" 1>&2
		exit 2
	fi
fi

echo "Creating mountpoint (/mnt/ssh/$1 ) mapping to $MP"
mkdir "/mnt/ssh/$1"
echo $MP > ~/.config/sshfs/$1
echo "testing..."
2f $1
